
import type {Metadata} from 'next';
import { Inter } from 'next/font/google'; // Changed from Geist
import './globals.css';
import { MobileNav } from '@/components/custom/mobile-nav';

const inter = Inter({ // Changed from geistSans
  variable: '--font-inter', // Changed variable name
  subsets: ['latin'],
});

// Removed geistMono

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.variable} font-sans antialiased`} suppressHydrationWarning={true}> {/* Updated class to use Inter and apply font-sans, and added suppressHydrationWarning */}
        <div className="min-h-screen pb-16 md:pb-0"> {/* Add padding-bottom for mobile to avoid overlap with MobileNav */}
          {children}
        </div>
        <MobileNav />
      </body>
    </html>
  );
}
